FROM microsoft/dotnet:2.2.104-sdk as build

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \ 
	&& apt update \
    && apt install -y nodejs \
    && apt install -y dos2unix

ENV ASPNETCORE_URLS http://*:9341

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY ./src/ui /ui/
COPY ./src/api/api.csproj /api/
COPY ./src/api /api/
COPY ./docker_entrypoint.sh /

WORKDIR ui
RUN npm install

WORKDIR /
WORKDIR api/
RUN dotnet restore api.csproj
RUN dotnet publish -c $BUILDCONFIG -o out /p:Version=$VERSION

WORKDIR /

RUN dos2unix docker_entrypoint.sh
RUN chmod +x docker_entrypoint.sh

EXPOSE 80
# EXPOSE 9341

CMD ["./docker_entrypoint.sh"]
